name: flutter_map_location
description: flutter_map plugin to request and display the users location and heading on the map.
version: 0.8.0
homepage: https://github.com/Xennis/flutter_map_location

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_compass: ^0.6.0
  flutter_map:
    git:
      url: https://github.com/fleaflet/flutter_map.git
      # Do not upgrade further because of https://github.com/fleaflet/flutter_map/issues/887
      ref: f9ad2881d302b4a3b5b25f207793ad9f4b961ad3
  latlong2: ^0.8.0
  location: ^4.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

publish_to: none